### ISSUE TITLE
window平台下start报错

### ISSUE THREAD

**Issue by note520** [wxyyxc1992/webpack-app-template#14]
**nmp logs:**
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start',
1 verbose cli   '--scripts-prepend-node-path=auto' ]
2 info using npm@3.10.10
3 info using node@v6.11.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle react-boilerplate@0.0.14~prestart: react-boilerplate@0.0.14
6 silly lifecycle react-boilerplate@0.0.14~prestart: no script for prestart, continuing
7 info lifecycle react-boilerplate@0.0.14~start: react-boilerplate@0.0.14
8 verbose lifecycle react-boilerplate@0.0.14~start: unsafe-perm in lifecycle true
9 verbose lifecycle react-boilerplate@0.0.14~start: PATH: D:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;D:\www\GitHub\create-webpack-app\react\node_modules\.bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Python27\;C:\Python27\Scripts;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0\;C:\Program Files (x86)\Windows Kits\8.0\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Python27;C:\WINDOWS\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Git\cmd;D:\ProgramData\adtbundlewindows\sdk\tools;D:\ProgramData\adtbundlewindows\sdk\platform-tools;C:\Python27;C:\Program Files (x86)\Java\jdk1.8.0_73\bin;D:\Program Files\TortoiseSVN\bin;D:\Program Files\phpfind\phpb;C:\ProgramData\ComposerSetup\bin;D:\Program Files\apache-maven-3.3.9\bin;D:\Program Files (x86)\HashiCorp\Vagrant\bin;D:\Program Files\nodejs\;C:\Ruby23-x64\bin;C:\Users\YTYT\AppData\Roaming\Composer\vendor\bin;C:\Users\YTYT\AppData\Roaming\npm
10 verbose lifecycle react-boilerplate@0.0.14~start: CWD: D:\www\GitHub\create-webpack-app\react
11 silly lifecycle react-boilerplate@0.0.14~start: Args: [ '/d /s /c',
11 silly lifecycle   'better-npm-run start:dll && better-npm-run start:dev' ]
12 silly lifecycle react-boilerplate@0.0.14~start: Returned: code: 1  signal: null
13 info lifecycle react-boilerplate@0.0.14~start: Failed to exec start script
14 verbose stack Error: react-boilerplate@0.0.14 start: `better-npm-run start:dll && better-npm-run start:dev`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (D:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (D:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:891:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid react-boilerplate@0.0.14
16 verbose cwd D:\www\GitHub\create-webpack-app\react
17 error Windows_NT 10.0.10586
18 error argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start" "--scripts-prepend-node-path=auto"
19 error node v6.11.1
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error react-boilerplate@0.0.14 start: `better-npm-run start:dll && better-npm-run start:dev`
22 error Exit status 1
23 error Failed at the react-boilerplate@0.0.14 start script 'better-npm-run start:dll && better-npm-run start:dev'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the react-boilerplate package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     better-npm-run start:dll && better-npm-run start:dev
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs react-boilerplate
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls react-boilerplate
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**cmd下**
to be executed: "./node_modules/.bin/webpack  --config ./dev-config/webpack.dll.config.js"
'.' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start" "--scripts-prepend-node-path=auto"

**Comment by wxyyxc1992** [comment]
竟然直接乱码，我等下找个 Windows 机器调试下看看

**Comment by ChiaJune** [comment]
我使用`npm start`也报错。

`npm install better-npm-run -g`  这个命令是`yarn install`完就执行了的

错误信息：

``` bash
Executing script: start:dll

to be executed: "./node_modules/.bin/webpack  --config ./dev-config/webpack.dll.config.js"
'.' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! react-boilerplate@0.0.14 start: `better-npm-run start:dll && better-npm-run start:dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-boilerplate@0.0.14 start script 'better-npm-run start:dll && better-npm-run start:dev'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     better-npm-run start:dll && better-npm-run start:dev
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\Projects\React\create-webpack-app\react\npm-debug.log
```

## 不知道作者还在维护这个项目么？
